"""Generate Cesarewitch-V2.0-Build-Audit.md from the pipeline outputs (tables are never hand-typed)."""
import os, sys, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import numpy as np, pandas as pd
import warnings; warnings.filterwarnings('ignore')
import backtest as B
HERE = os.path.dirname(os.path.abspath(__file__))
def md(df):
    df = df.copy(); cols = list(df.columns)
    out = ['| ' + ' | '.join(map(str, cols)) + ' |', '|' + '|'.join('---' for _ in cols) + '|']
    for _, r in df.iterrows(): out.append('| ' + ' | '.join('' if (isinstance(v, float) and np.isnan(v)) else (f'{v:.2f}' if isinstance(v, float) else str(v)) for v in r) + ' |')
    return '\n'.join(out)

feat = pd.read_csv(f'{HERE}/cesarewitch_runner_features.csv')
sep = pd.read_csv(f'{HERE}/phase2_separation.csv')
eff = B.effects(); w = B.weights(eff); card = B.build_card(w); sc = B.score(feat, card)
card_j = json.load(open(f'{HERE}/card_v2.json'))
ck = pd.read_csv(f'{HERE}/calibration_k.csv'); lc = pd.read_csv(f'{HERE}/calibration_lambda.csv')
loy = B.loyo(feat, None)
perm = open(f'{HERE}/perm_result.txt').read() if os.path.exists(f'{HERE}/perm_result.txt') else '(not run)'

# ---- tables
t3 = sep[['attr','eff_pct','std_sep','dir','consistent_yrs','top2_conc','pct_by_year','verdict','fieldwide_rho','eff_pct_ex22','verdict_ex22','corr_filter']].rename(
    columns={'attr':'Attribute','eff_pct':'Winner pctile (dir.-adj)','std_sep':'Std sep','dir':'Dir','consistent_yrs':'Consistent','top2_conc':'Top-2 conc %',
             'pct_by_year':'Pctile 22/23/24/25','verdict':'Verdict','fieldwide_rho':'Field-wide ρ','eff_pct_ex22':'Pctile ex-2022','verdict_ex22':'Verdict ex-2022','corr_filter':'Corr filter'})
rows = []
for yr, g in sc.groupby('year'):
    s = B.race_stats(g, card)
    rows.append({'Year': yr, 'Winner': s['winner'], 'Rank (avg ties)': f"{s['rank_avg']:.1f}/{s['N']}", 'Score': f"{s['win_score']:.0f}", 'Top score': f"{s['top_score']:.0f}",
                 'Range': f"{s['range']:.0f}", 'IQR': f"{s['iqr']:.1f}", 'Max top-2-band share': f"{max(s['comp'].values())*100:.0f}%", 'Gate': 'PASS' if s['gate'] else 'FAIL'})
bt = pd.DataFrame(rows)
fields = []
for yr, g in sc.sort_values(['year','total'], ascending=[True,False]).groupby('year'):
    g = g.reset_index(drop=True); g['Pos'] = range(1, len(g)+1)
    t = g[['Pos','horse','winner','total','pts_f_winrate16','pts_dual_career','pts_wins_365d','pts_form_trend3','n_na','finish_pos']].copy()
    t.columns = ['Rank','Runner','W','Score','Staying WR','Jumps','Wins 12m','Trajectory','NA','Actual finish']
    t['W'] = t['W'].map({1:'**WIN**',0:''}); fields.append(f'### {yr} ({len(g)} runners)\n\n' + md(t))
occ = []
for f in B.FACTORS:
    idx = feat[f].map(lambda x: np.nan if pd.isna(x) else B.band_index(f, x)); o = idx.value_counts(normalize=True).sort_index()
    for i, v in o.items(): occ.append({'Factor': f, 'Band': B.BANDS[f][int(i)][0], 'Points': card[f][int(i)], 'Pooled share %': round(v*100)})
spec = pd.DataFrame(occ)
ckt = ck[['k','logloss','brier','avg_leader_p','leader_strike','ll_by_year']].rename(columns={'logloss':'Log loss','brier':'Brier','avg_leader_p':'Avg leader p','leader_strike':'Leader strike','ll_by_year':'LL by year 22/23/24/25'})
corr = pd.read_csv(f'{HERE}/phase2_spearman.csv', index_col=0).loc[B.FACTORS, B.FACTORS].round(2).reset_index().rename(columns={'index':''})
wtab = pd.DataFrame({'Factor': B.FACTORS, 'Effect (std sep × consistency)': eff.values.round(3), 'Weight': [int(w[f]) for f in B.FACTORS], 'Bands→points': [' / '.join(map(str, card[f])) for f in B.FACTORS]})
n_strong = (sep.verdict=='STRONG').sum(); n_cond = (sep.verdict=='CONDITIONAL').sum(); n_rej = (sep.verdict=='REJECTED').sum()

doc = f"""# Cesarewitch Handicap — V2.0 Data-Up Build Audit

**Status: PROVISIONAL / IN-SAMPLE ONLY.** Not yet applied to a live renewal. Supersedes V1.0 (failed backtest).
Governance: Flat Race Analysis V4.4. Family: Heritage Handicap | Class 2 | 3YO+ | Newmarket Rowley Mile | 2m2f (3,960y) | Turf.
Date: 7 October 2026. Everything below is regenerated by `build_audit.py` from `extract.py` → `separation.py` → `backtest.py`.

## 1. Headline

* Built from runner-level data (95 runners, 2022–2025), not trend headlines.
* The data is **thin**: four winners. Of {len(sep)} candidate attributes, {n_strong} are STRONG, {n_cond} CONDITIONAL, {n_rej} REJECTED under the brief's §5.2 rules, and most "strong" ones are noise-prone (see §8).
* The card has **4 factors** (brief allows 4–6; only four survive every filter) and covers four causal domains.
* In-sample: winner ranked **{', '.join(f"{r['Rank (avg ties)']}" for _, r in bt.iterrows())}** (2022–2025). Top half 3/4, top 5 in 2/4, top 3 in 2/4, compression gate 4/4 — minimums met, but the §8 permutation control shows a selection procedure run on random winners does as well or better (69% of shuffles reach 4/4 top-half), so these results are **not evidence of skill**.
* One brief requirement could **not** be met by data: no race-record-only factor separates (§5).
* The 2014–2021 cross-check could only be done partially from public sources (§7).

## 2. Data and quality notes

* All 8 RFB files used (484,246 runner rows, 1 Jan 2022 – 31 Dec 2025). Cesarewitch IDs 44842126 / 45213126 / 45577128 / 45941119 → 21 / 31 / 24 / 19 runners (95).
* Files are UTF-8 bytes decoded as Latin-1 (fractions arrive as `Â½`); the parser strips `Â`. All `DstBtn` values now parse (0 failures). Beaten distance in features uses `TotalBtn` (cumulative).
* Class values above 6 (47, 50 — 67 rows) are treated as missing. Irish races mostly lack Class → NA.
* **History censoring.** RFB starts 1 Jan 2022, so "career" means career-since-Jan-2022: ~9 months of history for 2022 runners, ~21 / ~33 / ~45 months for 2023 / 2024 / 2025. The 2022 winner (Run For Oscar) has only 3 prior runs. Jumps-experience prevalence rises 29% → 39% → 50% → 68% across the years for this reason. Phase 2 was therefore re-run excluding 2022 as a robustness check (columns "ex-2022").
* Horse identity = RFB horse name (including country suffix); no cross-name resolution was attempted.
* The "career staying record (Flat, excluding latest)" counts exclude the single most recent run overall, as briefed.
* Banned from the factor search per §4.2: OR as score input, weight, draw, trainer, jockey, price/market, going, course form. `or_entry` is carried as a reference column only; `or_chg3` (OR change) was a candidate but is OR-derived and 8–29% NA.

## 3. Phase 2 separation table (evidence base)

Method per brief §5: winner percentile rank per year (mid-rank) averaged; standardised separation = (winner − field median)/field IQR averaged; direction consistency (winner on the favourable side of the median, binary attributes: winner holds the favourable level); compression = share of the pooled field in the top two bands *in the favourable direction* (≤6 distinct values: each value a band; else 5 equal-width bands; binary: prevalence of the favourable level). STRONG = passes all of (pctile >60, consistent ≥3/4, top-2 <70%); CONDITIONAL = two; REJECTED otherwise. Correlation filter: Spearman >0.70 → keep the better-separating attribute. Additional columns, not in the brief: **Field-wide ρ** (mean within-race Spearman between attribute and finishing position over all 95 runners, signed so positive = attribute points the same way as the winner direction) and **ex-2022** robustness.

{md(t3)}

Spearman correlations among the four selected factors:

{md(corr)}

## 4. Factor selection

Procedure applied to the STRONG/CONDITIONAL, correlation-surviving candidates:

1. **Field-wide support filter (declared before weighting; grounds: brief §7.3 "must separate across the field distribution, not just at the winner's data point").** Require Field-wide ρ ≥ +0.05 in the winner direction. This removes `l_yards` (ρ 0.00), `r2_btn` (−0.01) and `l_field` (−0.06): they separate the four winners from medians but carry no signal across the other 91 runners. This is an addition to §5.2, flagged here.
2. **One fact, one home / domain coverage.** `f_runs16` (STRONG, ρ 0.06) is the same domain as `f_winrate16` (career staying record) and was not admitted. `form_trend3` (ρ 0.11) contains the latest finish, so `l_pprop` (ρ −0.66 with it) was not also admitted. `dual_career`/`j_any` correlate ≈1.0; `dual_career` separates better.
3. `or_chg3` (OR-derived, up to 29% NA) not admitted.

Admitted:

| Factor | Domain | Verdict | Note |
|---|---|---|---|
| Staying win rate (`f_winrate16`) | Career staying record | STRONG | best separator; ex-2022 84th pctile 3/3 |
| Jumps experience (`dual_career`) | Dual-purpose profile | STRONG | largest field-wide ρ (0.31); 2022 winner is the one without, but his history is censored |
| Wins in last 12 months (`wins_365d`) | Current form / momentum | CONDITIONAL | 2/4 consistency; included at reduced weight by the effect formula |
| Form trajectory (`form_trend3`) | Form trajectory | STRONG (all-years) / REJECTED ex-2022 | **weakest factor**; ρ 0.11 |

Domains covered: career staying, dual-purpose profile, momentum, trajectory (≥3 required ✓).

**Not met: §6.1(4)** (one factor extractable from the Cesarewitch race record alone). The only race-record-only attributes (age; last Form figure; Form-string trend; days) all fail the §5.2 criteria (e.g. `rr_form_trend3`: 56th percentile, 2/4). Admitting one would break the "data beats headlines" rule, so the card requires RFB history for all four factors. Missing evidence is handled as NA with active-field mean imputation (never zero) and the card is labelled PROVISIONAL for that runner.

## 5. Weights (§6.2) and bands (§6.3) — the V2.0 Anchored 100 (§6)

Weights ∝ effect (standardised separation × consistency), capped at 40, floor 5, largest-remainder rounding to 100:

{md(wtab)}

Bands: quartile-style edges on the pooled 95-runner distribution (not winners' values), rounded. Top band = max, bottom = 1, intermediate bands evenly spaced. All bands ≥5% of pool; top-two-band share <70% for every ≥3-band factor.

{md(spec)}

NA counts in the pool: staying win rate 4, form trajectory 5, others 0.

**Two-band factor (jumps experience).** A two-band factor's "top two bands" would be 100% by construction, so the compression test applies to its top band (prevalence of jumps experience, 29% / 39% / 46% / 68% by year — passes, but 2025 is close to the 70% limit and will rise as the data window grows; **re-check the band at V2.1**).

## 6. Backtest (§7) — in-sample, PROVISIONAL

{md(bt)}

Success criteria: top half **3/4** (min 3, target 4); top 5 **2/4** (min 2); top 3 **2/4** (min 1); gate **4/4**; range ≥20 every year (**{int(min(B.race_stats(g, card)['range'] for _, g in sc.groupby('year')))}** minimum) ✓.

**Irreducible outlier: 2022 Run For Oscar (13th of 21).** He has 3 prior runs in the data (history window ~9 months), no jumps run, and a staying win rate of 0 from a censored record. The card can't see what the data doesn't contain; no band was adjusted for him (brief §10 no winner-chasing).

Full ranked fields with factor breakdowns are in `backtest_ranked_fields.csv`; reproduced here:

{chr(10).join(fields)}

## 7. Cross-check, 2014–2021 winners (§8) — PARTIAL

Reconstructing pre-race profiles needs run-by-run data. The public sources reachable in this build (news and previews) give dual-purpose status and last-run narratives, not position/distance lists, so **only the jumps-experience factor (24 pts) can be scored, and only where sources or the brief itself support it.** The other three factors are NA and no score was fabricated.

| Year | Winner | Jumps experience | Basis |
|---|---|---|---|
| 2021 | Buzz | Yes (hurdles, Henderson) | public reports: Flat with Morrison, then hurdles from 2019 |
| 2020 | Great White Shark | Yes | brief: dual-purpose |
| 2019 | Stratum | Yes | public reports: last run a Listowel hurdle, before that a Flat win at Killarney |
| 2018 | Low Sun | NA | not verified |
| 2017 | Withhold | No | brief: Flat-only |
| 2016 | Sweet Selection | No | brief: Flat-only |
| 2015 | Grumeti | Yes | brief: dual-purpose |
| 2014 | Big Easy | Yes | brief: dual-purpose |

Result: 5 of 7 verifiable winners had jumps experience (plus 3 of 4 in-sample = 8 of 11, vs pooled field prevalence 44%), so this factor does not misfire on older renewals; the two Flat-only winners (Withhold, Sweet Selection, both 4YOs) are exactly the "progressive improver" type that this card scores lower on jumps experience. No adjustment is triggered (a single-factor miss by two winners of a different type is a **band review flag**, not a change, under §8.3, and the factor already shows data separation). **The full 8-winner scoring, and the check for a missing factor, remain open** — they need RFB-style data for 2014–2021 or manually verified Racing Post profiles.

## 8. Overfitting controls (§7.3)

### Leave-one-year-out (weights recomputed from the other three years, same band edges)

{md(loy.assign(rank=loy['rank'].map('{:.1f}'.format)))}

Held-out rank: top half in {int((loy['rank'] <= loy['N']/2).sum())}/4 years. Weights are **unstable** (e.g. wins-in-12-months weight swings 5–40), which is expected with four winners; the sign pattern (staying win rate dominant) is stable, the rest is not.

### Selection-bias permutation test

The Phase 2 selection (top four non-rejected attributes by effect, generic percentile scoring) was run on randomly assigned winners (300 shuffles, within-race):

```
{perm}
```

**Reading: the in-sample result is not evidence of predictive skill.** Running the same selection on randomly assigned winners gives a mean winner rank percentile of 0.18 (better than the real card's 0.22), and a null card reaches a top-half rate of 4/4 in 69% of shuffles. With ~50 candidate attributes and four winners, a selection procedure can almost always find four attributes that fit those winners. (The test uses generic within-race percentile scoring rather than the banded card, and no field-wide filter, so it is a proxy, but the gap is too large for that to rescue the result.) The only features with independent support are those with field-wide signal across all 95 runners (jumps experience ρ 0.31, staying win rate 0.16), which is why the field-wide filter was applied. Do not size bets on this card on the strength of the backtest; the first live renewals are the real test.

## 9. Compression gate pre-check (§6.4)

Range ≥20 and IQR ≥8 pass in all four years (see §6); no ≥10-point factor has ≥70% of a field in its top two bands (jumps experience, top band only, peaks at 68% in 2025). Gate: **4/4**.

## 10. k / λ calibration (§9.1)

Probability line: `p_i ∝ exp(k × (score_i − top)/100)`, then `p = (1−λ)·p + λ/N`. Four renewals only, so this is indicative.

{md(ckt)}

* Log loss is flat between k = 4.5 and 6.0 (min 5.0–5.5); Brier keeps falling to k = 8 because it rewards confident leaders and the leader strike rate (2/4 = 50%) exceeds the average leader probability (24% at k=5). Choosing the conservative (lower-k) side of the stable region: **k = 5.0**.
* Year-on-year stability is poor: the 2022 log loss worsens with k (3.4 → 5.6) while 2024/2025 improve (2.5 → 0.7). That is the 2022 outlier, and it argues against going above 5.
* λ at k = 5.0:

{md(lc)}

λ > 0 improves log loss trivially (2.561 → 2.554 at 0.10) and worsens Brier; not material → **λ = 0** frozen.

## 11. Deliverables

`extract.py` (D1), `separation.py` + `phase2_separation.csv` (D2), `card_v2.json`, `backtest.py` + `backtest_ranked_fields.csv` (D3/D4/D9), `perm_test.py`, this audit (D7), `Cesarewitch-V2.0-Reusable-Scorecard.html` (D8).

## 12. Validation checklist

- [x] Maxima sum to 100; bands ordered (asserted in the HTML).
- [x] HTML run headless in Chromium: no console errors; 2025 Beylerbeyi and Mordor re-scored in the browser (95 / 74) match Python.
- [x] Missing-evidence handling: NA → active-field mean, PROVISIONAL flag shown.
- [x] No price, odds, OR-as-score, weight, draw, trainer/jockey, going or course input in the 100.
- [x] Band edges from the pooled distribution; ≥5% per band.
- [x] Compression gate 4/4 years.
- [ ] §6.1(4) race-record-only factor — **not met** (no attribute separates).
- [ ] Full 2014–2021 cross-check — **partial** (jumps experience only).
- [ ] Live-renewal confirmation — outstanding (status stays PROVISIONAL).

## 13. Status rule (§9.4)

CONFIRMED after one live renewal if the winner is in the top half and the gate passes; otherwise FLAGGED FOR V2.1 REVIEW. Three convergent findings are required before changing weights, bands or k/λ.

## 15. Interaction audit log

| Date | Event |
|---|---|
| 7 Oct 2026 | V1.0 (six-factor trend-headline card) declared failed: winners ranked 17th, 21st, 5th, 15th (V2 weights); rebalance to V3 weights left 3 of 4 outside the top 5. Cause: factors described entry conditions, so scores compressed. |
| 7 Oct 2026 | V2.0 data-up rebuild commissioned. |
| 7 Oct 2026 | First delivery had only 5 of 8 RFB files; build paused until RFB2022A / 2023A / 2023B arrived (two-year fit would have been meaningless). |
| 7 Oct 2026 | Parser fix: files are UTF-8 read as Latin-1 (`Â½`), so all fractional beaten distances initially failed to parse; fixed before any analysis. |
| 7 Oct 2026 | Separation tool fix: compression measured in the favourable direction; binary attributes tested on prevalence; numpy bool addition bug (`True+True`) that mis-graded attributes caught and fixed before selection. |
| 7 Oct 2026 | Field-wide support filter added to selection (grounds: §7.3), declared before weighting. |
| 7 Oct 2026 | V2.0 card frozen as PROVISIONAL: 4 factors, k=5.0, λ=0. |

## 16. Known limitations (read before use)

1. Four winners. Weights are unstable under leave-one-year-out; treat the point values as a ranking device, not calibrated probabilities.
2. History is censored at Jan 2022: 2022 features describe ~9 months, and the same card applied to a 2026 field will see full 4-year history, so the jumps-experience band will hold more runners than any backtest year (re-check compression on the live field).
3. Form trajectory is the weakest factor (rejected when 2022 is excluded).
4. No race-record-only fallback exists; runners without RFB history are PROVISIONAL.
5. Race-day overlays (draw, going, course form, trainer/jockey, pace, equipment) remain outside the 100.
"""
open(f'{HERE}/Cesarewitch-V2.0-Build-Audit.md', 'w').write(doc)
print(len(doc))
